## This programme helps to finish the USL Asm 2

In [8]:
import numpy as np

In [9]:
X = np.array([[1.5, 3], [1.6, 1.2], [1.1, 1], [3.7, 1.8], [4.2, 2.5], [2.7, 3], [3.1, 2]])

mu = np.array([[1.4, 1.6], [2.5, 1.3], [3, 1.3]])

In [16]:
print("Original X: ")
print(X)

Original X: 
[[1.5 3. ]
 [1.6 1.2]
 [1.1 1. ]
 [3.7 1.8]
 [4.2 2.5]
 [2.7 3. ]
 [3.1 2. ]]


In [66]:
X_distance = []
for i in range(0, 3):
  print(f"Distance between X and mu{i+1}: ")
  temp = np.sqrt(np.sum((X-mu[i])**2, axis=1))
  X_distance.append(temp)
  print(temp)

print("Items belong to the class: ")
temp = np.argmin(X_distance, axis=0) 
temp = np.array(temp)
print(temp)

new_mu1 = [0,0,0]

for i in range(3):
  t = X[temp==i]
  new_mu1[i] = np.mean(t, axis=0)

new_mu1 = np.array(new_mu1)
print("New mu: ")
print(new_mu1)

Distance between X and mu1: 
[1.40356688 0.4472136  0.67082039 2.30867928 2.94108823 1.91049732
 1.74642492]
Distance between X and mu2: 
[1.97230829 0.90553851 1.43178211 1.3        2.0808652  1.71172428
 0.92195445]
Distance between X and mu3: 
[2.26715681 1.40356688 1.92353841 0.86023253 1.69705627 1.72626765
 0.70710678]
Items belong to the class: 
[0 0 0 2 2 1 2]
New mu: 
[[1.4        1.73333333]
 [2.7        3.        ]
 [3.66666667 2.1       ]]


In [67]:
X_distance = []
for i in range(0, 3):
  print(f"Distance between X and mu{i+1}: ")
  temp = np.sqrt(np.sum((X-new_mu1[i])**2, axis=1))
  X_distance.append(temp)
  print(temp)

print("Items belong to the class: ")
temp = np.argmin(X_distance, axis=0) 
temp = np.array(temp)
print(temp)

new_mu1 = [0,0,0]

for i in range(3):
  t = X[temp==i]
  new_mu1[i] = np.mean(t, axis=0)

new_mu1 = np.array(new_mu1)
print("New mu: ")
print(new_mu1)

Distance between X and mu1: 
[1.2706079  0.56960025 0.79232429 2.30096598 2.90306352 1.81506045
 1.72078793]
Distance between X and mu2: 
[1.2        2.10950231 2.56124969 1.56204994 1.58113883 0.
 1.07703296]
Distance between X and mu3: 
[2.34615525 2.25413201 2.79245014 0.30184617 0.66666667 1.32077418
 0.57542255]
Items belong to the class: 
[1 0 0 2 2 1 2]
New mu: 
[[1.35       1.1       ]
 [2.1        3.        ]
 [3.66666667 2.1       ]]
